"""memes_image

Revision ID: 8b915967b6fb
Revises: 49c4023f3d1d
Create Date: 2024-08-04 03:30:46.864176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b915967b6fb'
down_revision: Union[str, None] = '49c4023f3d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'image_path')
    # ### end Alembic commands ###
