version: '3'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    restart: always
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB} || 1" ]
      interval: 10s
      timeout: 5s
      start_period: 5s
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3_storage:
    image: minio/minio:latest
    container_name: s3_storage
    restart: always
    hostname: images
    command: server /data/ --address "images:${S3_PORT}" --console-address ":${S3_CONSOLE_PORT}"
    healthcheck:
      test: mc ready local
      interval: 10s
      timeout: 5s
      start_period: 10s
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    ports:
      - "${S3_PORT}:${S3_PORT}"
      - "${S3_CONSOLE_PORT}:${S3_CONSOLE_PORT}"
    volumes:
      - s3_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${APP_PORT}/api/v1/healthcheck || 1" ]
      interval: 20s
      timeout: 5s
      start_period: 10s
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      s3_storage:
        condition: service_healthy
    ports:
      - '127.0.0.1:${APP_PORT}:${APP_PORT}'

volumes:
  postgres_data:
  s3_data: